### ISSUE TITLE
Failed Ansible Install Step:  restart jupyterhub with supervisor

### ISSUE THREAD

**Issue by jkuruzovich** [jupyterhub/jupyterhub-deploy-teaching#22]
When installing on UBUNTU Ansible goes through 63 steps successfully but then fails at the step below.  

TASK [jupyterhub : restart jupyterhub with supervisor] *************************
fatal: [notebooks.analyticsdojo.com]: FAILED! => {"changed": false, "failed": true, "msg": "jupyterhub: stopped\njupyterhub: ERROR (spawn error)\n"}

NO MORE HOSTS LEFT *************************************************************

RUNNING HANDLER [common : restart ntp] *****************************************

RUNNING HANDLER [nginx : reload nginx] *****************************************
 [WARNING]: Could not create retry file 'deploy.retry'.         [Errno 2] No such file or directory: ''

PLAY RECAP *********************************************************************
notebooks.analyticsdojo.com : ok=63   changed=54   unreachable=0    failed=1  

I've tried multiple times but haven't been able to get past this step.

Best,
Jason

**Comment by zonca** [comment]
I would try to ssh into the machine and run both supervisorctl restart and
reloading NGINX manually to have more details about the error.

**Comment by jkuruzovich** [comment]
Thank you! After further investigation of the logs I realized the error was from a user that had not been created on the server but was listed in the host file.
