### ISSUE TITLE
config-http-proxy not installing

### ISSUE THREAD

**Issue by ellisonbg** [jupyterhub/jupyterhub-deploy-teaching#26]
With a fresh deployment, I get an error:

```
[I 2016-10-02 15:50:13.731 JupyterHub app:624] Loading cookie_secret from /srv/jupyterhub/cookie_secret
[I 2016-10-02 15:50:13.819 JupyterHub app:1232] Hub API listening on http://127.0.0.1:8081/hub/
[W 2016-10-02 15:50:13.822 JupyterHub app:960] Running JupyterHub without SSL. There better be SSL termination happening somewhere else...
[I 2016-10-02 15:50:13.822 JupyterHub app:969] Starting proxy @ http://65.61.190.162:8000/
[E 2016-10-02 15:50:13.824 JupyterHub app:977] Failed to find proxy ['configurable-http-proxy']
    The proxy can be installed with `npm install -g configurable-http-proxy`
```

Running `conda list` does not show the configurable-http-proxy package.

@minrk @willingc any ideas?

**Comment by ellisonbg** [comment]
Hmm, running `conda install configurable-http-proxy` seems to work, don't know why it failed in the ansible stuff...

**Comment by willingc** [comment]
@ellisonbg Just to clarify... are you running 16.04 LTS or 14.04 LTS?

**Comment by ellisonbg** [comment]
14.04

**Comment by minrk** [comment]
@ellisonbg CHP is only packaged by conda-forge, so if it's failing, that could mean that the conda-forge channel is not enabled.

**Comment by minrk** [comment]
@ellisonbg how did you provision the server? Did you run anything prior to the deploy?

**Comment by ILoveDataSCIENCE8** [comment]
I got the same and was able to fix with the following.  I'm not 100% sure what is required.

ssh root@servername
8. apt install npm
9. git clone https://github.com/jupyter/configurable-http-proxy.git
10. cd configurable-http-proxy
11. sudo npm install -g
12. PATH="$PATH:/usr/local/bin" npm install -g bower less grunt-cli
13. sudo apt-get install nodejs-legacy
15. supervisorctl (if not running then supervisord)
16. start all

That for me got it to work.

**Comment by jkuruzovich** [comment]
I got the same error and  used the following and got it to work:

ssh root@servername
8. apt install npm
9. git clone https://github.com/jupyter/configurable-http-proxy.git
10. cd configurable-http-proxy
11. sudo npm install -g
12. PATH="$PATH:/usr/local/bin" npm install -g bower less grunt-cli
13. sudo apt-get install nodejs-legacy
15. supervisorctl (if not running then supervisord)
16. start all

I found this an issue on Ubuntu 16.04.

**Comment by ellisonbg** [comment]
@minrk it was a fresh 14.04 server on rackspace. I hadn't done _anything_ before I ran the ansible scripts. The only other thing I did was to change the ansible config file to run things as root (that is the user that rackspace uses).

**Comment by minrk** [comment]
What exact flavor of VM, setup? Did you use let's encrypt? I ran with the changes in #28 and it completed in one go on 14.04 and 16.04. The changes I made don't seem like they would be relevant to the issues you had, though.

Can you share your vars file (privately)? Maybe some choices you made caused it to take a different path than mine.

**Comment by willingc** [comment]
I'm wondering if this is perhaps a node installation issue with 14.04 and Rackspace.

https://nodejs.org/en/download/package-manager/

> The nodejs-legacy package installs a node symlink that is needed by many modules to build and run correctly. The Node.js modules available in the distribution official repositories do not need it.

Rackspace doc: https://developer.rackspace.com/sdks/node-js/

**Comment by minrk** [comment]
@willingc we don't install nodejs with apt, we install it with conda. The issue appears to be that @ellisonbg is not getting packages from conda-forge, where configurable-http-proxy is packaged.
