### ISSUE TITLE
nginx not restarting/loading new config

### ISSUE THREAD

**Issue by ellisonbg** [jupyterhub/jupyterhub-deploy-teaching#27]
A fresh deployment on ubuntu 14 LTS needed an extra `service nginx restart` before it would run.

@minrk @willingc

**Comment by minrk** [comment]
Thanks for the note! Might need to double-check that nginx reload is triggered after something that affects it (could be SSL, could be config)

**Comment by ellisonbg** [comment]
Thanks!
