### ISSUE TITLE
cull idle servers not working

### ISSUE THREAD

**Issue by ellisonbg** [jupyterhub/jupyterhub-deploy-teaching#31]
I have configured the cull idle servers and it doesn't seem to be working. Here is my config:

``` yaml
# Optionally cull idle single user servers
use_cull_idle_servers: true
# The username and API token for culling idle servers
# Create using something like `openssl rand -hex 32`
cull_idle_servers_owner: root
cull_idle_servers_hubapi_token: '8ddef1a469ffbe3a86deb60d664ca53bc2bbadcca1145889014ef214a9e9c6fb'
# The interval (in seconds) for checking for idle servers to cull
cull_every: 600
# The idle timeout (in seconds)
cull_timeout: 259200
```

Which leads to the following supervisord config:

```
environment=JPY_API_TOKEN='8ddef1a469ffbe3a86deb60d664ca53bc2bbadcca1145889014ef214a9e9c6fb'
command=/opt/conda/bin/python3 /srv/jupyterhub/cull_idle_servers.py --cull-every=600 --timeout=259200
redirect_stderr=true
stdout_logfile=/var/log/jupyterhub/cull_idle_servers.log
autostart=true
autorestart=false
stopasgroup=true
user=root
directory=/srv/jupyterhub
```

I have confirmed that the .py script is installed in `/srv/jupyterhub`. When starting cull idle servers I see the following in the log:

``` python
Traceback (most recent call last):
  File "/srv/jupyterhub/cull_idle_servers.py", line 76, in <module>
    loop.run_sync(cull)
  File "/opt/conda/lib/python3.5/site-packages/tornado/ioloop.py", line 457, in run_sync
    return future_cell[0].result()
  File "/opt/conda/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/srv/jupyterhub/cull_idle_servers.py", line 43, in cull_idle
    resp = yield client.fetch(req)
  File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/opt/conda/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
tornado.httpclient.HTTPError: HTTP 403: Forbidden
```

And the following lines in my jupyterhub config file:

``` python
c.JupyterHub.api_tokens.update({
    '8ddef1a469ffbe3a86deb60d664ca53bc2bbadcca1145889014ef214a9e9c6fb': 'root'
})
```

As far as I can tell, all of the things are in the right place, but it doesn't look like the API token is being accepted by the hub. Other odd bits:
- While the `host_vars` files takes a `cull_idle_servers_owner` (I am using root) that isn't used anywhere other than the jupyterhub config file. The user owning the cull idle server process is hardcoded to `root` in the supervisor config file.

JupyterHub itself is working fine on this system.

**Comment by minrk** [comment]
I'll look into it.

The cull-idle-servers user should be cleaned up a bit by the services stuff in 0.7 (I'll work on updating this to 0.7 this week). In general, the user _should_ be a real user of the Hub, e.g. 'ellisonbg' not 'root'. Can you try that? 0.7 distinguishes 'services' from 'users', so that won't matter anymore.

**Comment by minrk** [comment]
Yeah, you can't use `'root'` as the user for the API token, unless root is an admin user of the Hub. Change root to ellisonbg or some other admin, and it should work. I just did a test deployment and it does still work, as long as the user is an admin.

If you declare the user 'root' as an admin, this will also work, but you would be giving [this person](https://github.com/root) admin access to your Hub.
