### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by zonca** [jupyterhub/jupyterhub-deploy-teaching#36]
I think it would be useful to tag a release once the current open issues are resolved.
This way users know what version of this `ansible` deployment worked on their platform more easily.

What do you think?

**Comment by minrk** [comment]
Yup, and I'm planning to bump this to 0.7, so it's a good time to tag right before I do that.

**Comment by zonca** [comment]
@minrk do you have an update on your plan to tag a release?
I'd like to write a short tutorial on how to use this and I'd like to test and reference a specific release.

**Comment by minrk** [comment]
@zonca  I created an 0.6 branch prior to the update that pointed everything to 0.7. I think a branch is better suited than a release, so it can get bugfixes (no new features or updates or refactors). What do you think?

**Comment by zonca** [comment]
@minrk ok fine, a branch will do, thanks.
