### ISSUE TITLE
Test Ansible 2.2+ with Python 3 support

### ISSUE THREAD

**Issue by willingc** [jupyterhub/jupyterhub-deploy-teaching#48]
Testing instructions are found here:
http://docs.ansible.com/ansible/python_3_support.html

**Comment by willingc** [comment]
Update note: I was having ssh authentication issues with Ansible 2.2. Dropping back to Ansible 2.1 solved them. Reading the Ansible tracker it seems that 2.3 may resolve the issue. On hold here pending Ansible 2.3 release.

**Comment by minrk** [comment]
Thanks for the update!

**Comment by zonca** [comment]
just tested with Ansible 2.2.1.0 on Ubuntu 16.04 with Python 3, it worked fine

**Comment by willingc** [comment]
Thanks @zonca! That helps a bunch.
