### ISSUE TITLE
Allow jupyterhub to be restarted w/o stopping single user servers

### ISSUE THREAD

**Issue by ellisonbg** [jupyterhub/jupyterhub-deploy-teaching#62]
We are currently managing the jupyterhub process through supervisord. When jupyterhub is reconfigured and restarted through supervisord, the single user servers are killed. It would be very helpful to be able to reconfigure+restart the hub while leaving the single user servers alive. What would be needed to accomplish this?

@minrk @willingc

**Comment by ellisonbg** [comment]
Maybe as simple as setting `cleanup_proxy` and `cleanup_servers` to `False`? Will try that now...

**Comment by ellisonbg** [comment]
Yep, that did it. I will add a variable to the host vars file to configure this...very nice!!!

**Comment by willingc** [comment]
Great! Thanks @ellisonbg.

**Comment by ellisonbg** [comment]
Done in master...
