### ISSUE TITLE
Start to tag releases that follow jupyterhub versions

### ISSUE THREAD

**Issue by ellisonbg** [jupyterhub/jupyterhub-deploy-teaching#64]
After trying to get everything in this repo working well with jupyterhub 0.7.0, I think we should start to tag/release versions of this repo that follow the versions of jupyterhub. That will make it much easier for folks to know and understand which version of this repo are known to work with which versions of jupyterhub/nbgrader/etc.

@minrk @willingc @jhamrick

**Comment by minrk** [comment]
@zonca suggested this in #36. I created an 0.6 branch for this, which I created immediately before merging the 0.7 stuff. I went with a branch instead of a tag, so we can still push bugfixes, rather than freezing a particular tag.

**Comment by ellisonbg** [comment]
Sounds good, closing
